let votes = [
  "XDELQOKZUGMCBTWAJNPFRVIS",
  "IQKGUDCWMNLSABZEPVXFJRTO",
  "SFPUJWZABNRLQEMXKIGDVCTO",
  "FISQWOZAGXJDNLTKPRECVUBM",
  "BMXIRQOWJSLPDNGAEFKZTUVC",
  "SCUFTIAQMWNXBGZEOJVDLKRP",
  "LMNXWKDBTAGPFUCJSROIQZEV",
  "NVDICPQFBZLRGWTMXJOAUESK",
  "PGZRUWNFMKTVJSLCDEXOABIQ",
  "BFKNDXRIGWTVSUJOCMPZAEQL",
  "MJLDKRNWPQXUFSTEGCOBVAIZ",
  "VCIMLFJSPZTDRKBAGXWUOEQN",
  "TERGMVDPILNQSFJCAKZWXBOU",
  "KOPFCIDQSVAMRBLNTWUZXJGE",
  "NKWPJGUAFOTZIERXMSLBDCQV",
  "QUKLSIFCDVZEAMXGJNTWROPB",
  "DSAGZRFWTMJEILKOPUNQVXCB",
  "ARQIVZNCMBJGWUPKEOSLFTDX",
  "ESMATLNJKPRFGXWVUCOQDIZB",
  "QNGTVDFICPSKMWUJBOZELAXR",
  "JAOMTSGFQPDWKRNLUXEVBCIZ",
  "FORAQBEDSTNPUZICVXGWMKLJ",
  "UWAFSXITRMPEGVQDLZBCNJOK",
  "IKFOVMNWJLCZBUAGERQPXTSD",
  "SLEOPWNDBUVIGQJZMRACXTFK",
  "GTDKMOJSILNAVXFPZQCUWRBE",
  "AZGRVFJDEUSCNLTBXWQIPMOK",
  "VQPNUMCJKSBXWIAFTGDOEZRL",
  "PVNODUXIMJSGACQTWRFBKLZE",
  "QGKDUAIMEVTXSZFBJLOWNPRC",
  "MDUOXBVQJPSAGNIKLRFZTCWE",
  "FMRTEDKWPVLGBICXSNZAQJOU",
  "WUEFMGXSIRNAOPCBDLQTKJZV",
  "UDGSPEQVZOBMNICJKXTWALRF",
  "SFNWLTARVKPJQZMGUDBOICEX",
  "FSPCMAJZEKNRLDWBGOXQIUVT",
  "VRUOAMJQGFSIZNXLEPWTDCBK",
  "VNCMBRLKUPDISJEWOAZGTXFQ",
  "VGJQZXMPKEIRLTNODCABWFSU",
  "IMALJVBCXSQPOUGEKNTRFDWZ",
  "UPJBVKQOAIDGWEZRLTNSXFMC",
  "IUAPCZFWOQTXBSNLKGVRDMEJ",
  "DOIRNGMKJLEUCPTWZQSVXFAB",
  "VJMWTPZFOGBNIDCQAULERKSX",
  "OAISKWCDLVRQFGNZPUTJEMXB",
  "NBTGWMEUROJDCKAZLFQXISPV",
  "DSOBAIJXFWNTUVERGQMCLKPZ",
  "SBLFZOGCNDWPXAEKTVRJUMIQ",
  "EKWMAQNURJBZPLFDSGOVIXCT",
  "BKXRSNVMWGAPCIFLZJTEUQOD",
  "VQNWJSZTCPEURAKBLIXOFGMD",
  "TQKFDXCWIUARVBELNOPJZGMS",
  "MSCPWBTKQUFVDGEXROANJLIZ",
  "XFQVITPRZMONWCLKBUAJGSED",
  "MVKLRFQWICOPDJBUSTXNEZGA",
  "DMKBRGLONJEIFTXZPUACQWSV",
  "NKSJBQZORVFTXWAUCDLGEMIP",
  "JQUIXNBRDMOLGSTFVAZCPEWK",
  "MEBXTJUNVWCQAZGRLIKSPDFO",
  "EKNUQILMTDPOSFJZWXGVCARB",
  "JOZNFECPVSXRLGDUKQWBITAM",
  "UXNZISEGTCVABJMKFLWDQPOR",
  "IJCFLPGZRXQUMANODKBVSETW",
  "KCJQRFEWNGAMBIXZVLPDSUTO",
  "TMSEDRAUWZGQXJPIFVLCOBKN",
  "ZPRXJNOEKCGFUSDQAILWMVTB",
  "WTBXANSJLRKFEPOIVDMQUZCG",
  "IRLVZNQPECOJATFWUSDMGKBX",
  "BGMPAZOIKWCSUDJNXLTVREQF",
  "BZXSTPRMLEKWCFIVONGADUQJ",
  "UFGZCWTARKSBDJXPMVQIENOL",
  "ZBROLDUFMNQAPJEGITXWCSKV",
  "FWLJXQDTRCGNVUZMAPBKISEO",
  "SJXLKAVZCPBIEWFQTNODGRMU",
  "VAIBDLOEXGUZQWMPNSJTCRKF",
  "XFLMPECKOQINGWSZJRTVBADU",
  "ZAJCPMSKUBFWEXQDTVGNLORI",
  "FUVECNMKZWJBGXTDLPASIOQR",
  "COFKSVMTNLBWXAREZDQIJUGP",
  "TKRVFXUIONEALPCDSJGBZWQM",
  "VJNQLTARZSGCPOMFBUWIXKDE",
  "GMUSFBPDZATKWEQONXCJILVR",
  "RFNCLTQZXMSVWPIUBGDEAKOJ",
  "NARSWLXMEIGQCFBOVDUJPZTK",
  "OBZVJGSKDUCXAQWPIFNEMTRL",
  "RIEQDWFSLCGTPKNBAJUVMZOX",
  "GBAXDSVUEOJNTLPIRKZCWQMF",
  "ZOETNALWVPGXRIMQKDBFUSCJ",
  "NAMBJKFZQTOSGWCDPIRXLEUV",
  "NWQJUZMKIXCGDSBREFPATLOV",
  "KWAECTUZODSPIJMNLVQRXFBG",
  "JXPWZNOCGRDKLQITUSEVAFBM",
  "FNAXSLPRWUBMQJICZTVKDOEG",
  "GMAWSUXVPZINTODEBRJFKQLC",
  "FACUKTLWNJSXRQMEDZVGBOIP",
  "FXEGPVLUJDRNQMTOWSIKAZCB",
  "ZNEKOJXDVQSUFARMLWPGICTB",
  "IRSZQGUKVJXCANFWLOBDEMPT",
  "IUEDPRJFVGQSAXNOWCBMZTLK",
  "XGKLOPJVQCWTBMSNUZARIEDF",
  "VSOJUPRFDCNQXTLMBKIGZWEA",
  "UDGIKPAFNTZWCJRMSLVOXEQB",
  "GQOIULRNMCJVPFEAZBSDWKTX",
  "ZJUTMKIFXRSCOPENVGLBDAQW",
  "ZUQOBCPWNJKVARLTDEGIXFSM",
  "ADBOKTGCWFMNVUEZLRPIQJSX",
  "ALDVEQZKCTOJRWBMISPNXFGU",
  "CEGUFDRXLAVTQNWOKMPZIJBS",
  "EMBXCVQDJLNWSGIZPRAFTUKO",
  "KJSQEPNOVGRWZLUIADFBCTXM",
  "UWVFQEDASJBGXCNPTZIORMLK",
  "XFLCZSMJAVEPIQDRTUBNKGWO",
  "URFBQMVATJWEPDCNGSILOZXK",
  "ZLDPUVIWOJEXGNTQFRBKSACM",
  "IEQBVDUPNLCGJASFRXTWZOMK",
  "TVWMROKSUPCXNFEALDQZIGBJ",
  "GFKEZOICNTXPASMBJVRUWLDQ",
  "NVWKLBMQJFPIRCSDOZGTXEAU",
  "QANRCGLPMDZKFOTXBVJEIWUS",
  "UPCLXNVQZTRKMEBGAOSFDJWI",
  "PANMJZIFCWGKQDXSRUETOLVB",
  "JGWVNUXLKAEODTBZIQRCMPFS",
  "TEOMUIZFSXPGWLADRBQKJVCN",
  "XPFDJLGZAWEKTRVCMBNUSOQI",
  "OCQSTRKAZPIMUBNDGEXJVWLF",
  "MILWTBRAVGZODFJUCSPXQENK",
  "FREBOSZDPMCNUJXAVKIGLWQT",
  "TQWPUCERNGIBMXDZKJVASFOL",
  "APLDRMWCQNFUTSKXVEGJIZBO",
  "SUWEMPJNFITABXVOCRZLDQKG",
  "FGRZBWMUTIACNEJKVQPXDOSL",
  "PBUWQEIDOLXCRNFVSZJTKAMG",
  "BRFZUGVLWEJKNIASPMTXDQOC",
  "XLIPMTZQSUFVANKOGBEJDRCW",
  "GSCRPUAKMEIDBVOLQXWZNFTJ",
  "KCQMJXRWSFGNBDLAUOTEIVZP",
  "GKDPJSRMALVEXUNWOICTFQZB",
];

var rankTeams = function (votes) {
  let anxStr = "";
  let hashmap = new Map();
  for (var i = 0; i < votes[0].length; i++) {
    hashmap.set(votes[0][i], new Array(votes[0].length).fill(0));
  }
  for (var i = 0; i < votes.length; i++) {
    let tmpArr = votes[i].split("");
    for (var j = 0; j < tmpArr.length; j++) {
      let rankArr = hashmap.get(tmpArr[j]);
      rankArr[j] += 1;
    }
  }
  hashmap.forEach((value, key) => {
    let tmpStr = "";
    for (var i in value) {
      tmpStr += value[i];
    }
    hashmap.set(key, Number(tmpStr));
  });

  let finalArr = [...hashmap.entries()].sort().sort((a, b) => b[1] - a[1]);

  for (var i in finalArr) {
    anxStr += finalArr[i][0];
  }

  return anxStr;
};

console.log(rankTeams(votes));
